<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchBar</name>
   <tag></tag>
   <elementGuidId>dc6453cc-fc8f-41d0-96df-66b22e6a83f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.gLFyf.gsfi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='gLFyf gsfi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>input[title='Search']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@title='Search']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gLFyf gsfi</value>
   </webElementProperties>
</WebElementEntity>
