<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropdownObject</name>
   <tag></tag>
   <elementGuidId>9a8d22e8-6367-440c-a99d-fe33f614c253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='continents']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#continents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
